### ISSUE TITLE
Templater commands not executing correctly with QuickAdd

### ISSUE THREAD

**Issue by haha9527upup** [chhoumann/quickadd#787]
**Description:**

This issue arises after updating both the QuickAdd and Templater plugins to their latest versions. It did not occur previously. The problem is observed on both desktop and iPhone versions of Obsidian, which is also up-to-date.

When creating a new document using QuickAdd with a specific Templater template, the Templater commands within the template are not executed. Instead, the raw Templater code remains in the document (see left side of the image).

However, using the "Create new file from template" command successfully executes the Templater commands (see right side of the image).

**Key points:**

- Issue occurs after recent plugin updates.
- Affects both desktop and mobile (iPhone) versions.
- Obsidian is up-to-date.
- QuickAdd + Templater template = Templater commands fail.
- "Create new file from template" = Templater commands succeed.
- Images provide visual comparison.

![Image](https://github.com/user-attachments/assets/143b6f39-1eec-49d9-8d86-c15ec2ed6350)

**Comment by dmarcolongo** [comment]
I'm having the same issue on both Android and MacOS.

**Comment by chhoumann** [comment]
I've created a fix for this issue in PR #788. The problem occurred because Templater commands weren't being forced to execute when creating files through QuickAdd. By setting force=true when calling replaceTemplaterTemplatesInCreatedFile, we ensure Templater commands are properly executed regardless of Templater settings.

**Comment by executer9648** [comment]
Hi this issue stil happens ,however, not when creating new files rather when capturing text to an existing file

**Comment by chhoumann** [comment]
Hi @executer9648, can you give me an example of something that doesn't work?

**Comment by executer9648** [comment]
sure, 
i have a capture quick add with the following capture format 
```
([[<% tp.file.title %>]]) {{VALUE}} ⏳{{DATE:YYYY-MM-DD}}
```
this is configured to capture to a constant file to be formated as a task.
when i issue this capture the value and the date is presented good but the "tp.file.title" templater is shown in plain text.
i need to run the templater replace command after this capture to change the templater.
btw this first happend on 1.13 on 1.12 it works well

**Comment by dmarcolongo** [comment]
I confirm the issue with appending to a note. It seems to not execute the templater code inside <% %>.

<img width="502" alt="Image" src="https://github.com/user-attachments/assets/583fcdd2-4d72-447d-bc2b-f666198e987e" />

<img width="798" alt="Image" src="https://github.com/user-attachments/assets/b3c9812c-37ec-4290-8159-3c63b8d8a9ac" />

**Comment by chhoumann** [comment]
I've pushed a fix that should address the issue with templater commands not executing properly in capture choices. The problem appears to be how we were handling templater command execution in different contexts. 

If you're able to test with the upcoming patch release (should be available soon), please let me know if it resolves the issue where templater code like `<% tp.file.title %>` was showing as plain text instead of executing. 

Thanks for your detailed reports and examples - they were very helpful in tracking this down.

**Comment by executer9648** [comment]
Hi @chhoumann it didnt fix the issue

**Comment by dmarcolongo** [comment]
> Hi [@chhoumann](https://github.com/chhoumann) it didnt fix the issue

It wan't released yet

**Comment by executer9648** [comment]
oh i saw an update yesterday, my bad then

**Comment by haha9527upup** [comment]
@executer9648  @chhoumann  I have update to 1.13.2 , 
The issue "Create new file from template"  has been fixed, but the "capturing text to an existing file" issue remains unresolved.

![Image](https://github.com/user-attachments/assets/8c64c437-b5c5-4ad4-983c-49835994240c)

![Image](https://github.com/user-attachments/assets/905097c1-fc48-432a-a5d3-5b4fa8724956)

**Comment by axelson** [comment]
Can this issue be re-opened since a portion of the issue is still ongoing?

**Comment by dmarcolongo** [comment]
I temp fix I have been doing is to trigger the command "Templater: Replace templates in the active file", but it dependes on the quick add action to have opened the file. Far from ideal but it is a workaround.

**Comment by dmarcolongo** [comment]
I have a notebar command to go to the current Weekly Note. The path is dynamic and given by The template. This workflow was working before the new update. 

![Image](https://github.com/user-attachments/assets/d07591b3-aba4-40bb-b60d-0a6a310252b7)
![Image](https://github.com/user-attachments/assets/ecf6b663-d215-4ab9-bd35-bff6d1b8c8ae)
![Image](https://github.com/user-attachments/assets/f5a84144-4281-4753-b09c-32930e6435c4)

**Comment by dmarcolongo** [comment]
But it did sem to fiz the original issue!
